bookshop/books/urls.py
from django.urls import path

from . import views

app_name = "books"

urlpatterns = [
    path("", views.BooksListView.as_view(), name="index"),
    path("books/<int:pk>/", views.BooksDetailView.as_view(), name="detail"),
    path(
        "books/search/",
        views.SearchResultsListView.as_view(),
        name="search_results"
    ),
]

bookshop/bookshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path("", include("books.urls", namespace="books")),
    path("cart/", include("cart.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]

# handler404 = 'core.views.page_not_found'
# handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    # urlpatterns += static(
    #     settings.STATIC_URL,
    #     document_root=settings.STATIC_ROOT
    # )

bookshop/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_view, name="cart_view"),
    path("add/<int:book_id>/", views.add_to_cart, name="add_to_cart"),
    path(
        "remove/<int:item_id>/",
        views.remove_from_cart,
        name="remove_from_cart"
    ),
    path('config/', views.stripe_config),
    path(
        'create-checkout-session/',
        views.create_checkout_session,
        name='checkout2'
    ),
    path('success/', views.SuccessView.as_view()),
    path('cancelled/', views.CancelledView.as_view()),
]

bookshop/books/models.py
from django.db import models
from django.core.validators import MinValueValidator


class Book(models.Model):
    title = models.CharField(max_length=150)
    author = models.CharField(max_length=100)
    price = models.FloatField(
        null=True, blank=True, validators=[MinValueValidator(0.01),]
    )
    publish_date = models.DateField()
    publisher = models.CharField(max_length=150)
    description = models.TextField(max_length=500, default=None, blank=True)
    # isbn = models.CharField()
    cover = models.ImageField(upload_to="covers/", blank=True, null=True)
    book_available = models.BooleanField(default=False)

    def __str__(self):
        return self.title

bookshop/books/views.py
from django.db.models import Q
from django.views.generic import DetailView, ListView

from bookshop.settings import BOOKS_PER_PAGE
from cart.models import Cart

from .models import Book


def get_total_items(request):
    if request.user.is_authenticated:
        cart = Cart.objects.filter(user=request.user).first()
        total_items = cart.total_quantity if cart else 0
    else:
        total_items = 0

    return total_items


class BooksListView(ListView):
    model = Book
    template_name = "books/index.html"
    paginate_by = BOOKS_PER_PAGE

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_items = get_total_items(self.request)
        context["total_items"] = total_items
        return context


class BooksDetailView(DetailView):
    model = Book
    template_name = "books/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_items = get_total_items(self.request)
        context["total_items"] = total_items
        return context


class SearchResultsListView(ListView):
    model = Book
    template_name = "books/search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        return Book.objects.filter(
            Q(title__icontains=query)
            | Q(author__icontains=query)
            | Q(publish_date__icontains=query)  # | Q(isbn__icontains=query)
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_items = get_total_items(self.request)
        context["total_items"] = total_items
        return context

bookshop/templates/books/detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Book Detail - {{ book.title }}{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {{ book.title }}
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              {% thumbnail book.cover "200x300" crop="center" upscale=False as im %}
                <img class="card-img" src="{{ im.url }}" alt="{{ book.title }}">
              {% endthumbnail %}
            </div>
            <div class="col-md-8">
              <p class="card-text">{{ book.description }}</p>
              <p><strong>Author:</strong> {{ book.author }}</p>
              <p><strong>Publisher:</strong> {{ book.publisher }}</p>
              <p><strong>Publish Date:</strong> {{ book.publish_date }}</p>
              <p><strong>Price:</strong> ${{ book.price|floatformat:2 }}</p>
              <div class="mt-4">
                {% if book.book_available is True %}
                <a href="{% url 'cart:add_to_cart' book.id %}" class="btn btn-primary">Add to Cart</a>
                {% else %}
                <h4 class="text-danger">Out of Stock</h4>
                {% endif %}
                <a href="{% url 'books:index' %}" class="btn btn-secondary ml-2">Back to Book List</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

bookshop/templates/books/index.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Bookshop - Home{% endblock %}

{% block content %}
  <h1>Book List</h1>
  <div class="row">
    {% for book in object_list %}
      <div class="col-md-3">
        <div class="card mb-3 shadow-sm">
          <div class="card-body">
            
            {% thumbnail book.cover "200x300" crop="center" upscale=False as im %}
              <img class="card-img" src="{{ im.url }}">
            {% endthumbnail %}
            <h5 class="card-title">{{ book.title|slice:":25" }}</h5>
            {% if book.book_available %}
              <h5 class="text-primary">Available</h5>
            {% else %}
              <h5 class="text-danger">Out of Stock</h5>
            {% endif %}
            <br>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'books:detail' book.id %}" class="btn btn-sm btn-outline-secondary">View</a>
                {% if book.book_available %}
                  <a href="{% url 'cart:add_to_cart' book.id %}" class="btn btn-sm btn-outline-primary">Add to Cart</a>
                {% endif %}
              </div>
              <small class="text-muted">${{ book.price|floatformat:2 }}</small>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

{% include 'books/includes/paginator.html' %}
{% endblock %}

bookshop/templates/books/search_results.html
{% extends 'base.html' %}

{% block title %}Search{% endblock title %}

{% block content %}

    <h3 class = "text-secondary">Search Results</h3><hr>

    {% for every in object_list %}
        <div>
            <h3><a href="{% url 'books:detail' every.pk %}">{{ every.title }}</a></h3>
            <p>Author: {{ every.author }}</p>
        </div>
    {% empty %}
    <h5 class="text-danger">Nothing found</h5>
    {% endfor %}

{% endblock content %}