bookshop/books/urls.py
from django.urls import path

from . import views

app_name = "books"

urlpatterns = [
    path("", views.BooksListView.as_view(), name="index"),
    path("books/<int:pk>/", views.BooksDetailView.as_view(), name="detail"),
    path(
        "books/search/",
        views.SearchResultsListView.as_view(),
        name="search_results"
    ),
]

bookshop/bookshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path("", include("books.urls", namespace="books")),
    path("cart/", include("cart.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]

# handler404 = 'core.views.page_not_found'
# handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    # urlpatterns += static(
    #     settings.STATIC_URL,
    #     document_root=settings.STATIC_ROOT
    # )

bookshop/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_view, name="cart_view"),
    path("add/<int:book_id>/", views.add_to_cart, name="add_to_cart"),
    path(
        "remove/<int:item_id>/",
        views.remove_from_cart,
        name="remove_from_cart"
    ),
    path('config/', views.stripe_config),
    path(
        'create-checkout-session/',
        views.create_checkout_session,
        name='checkout2'
    ),
    path('success/', views.SuccessView.as_view()),
    path('cancelled/', views.CancelledView.as_view()),
]

bookshop/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© Test <span style="color:rgb(17, 0, 255)">Book</span>shop</p>
</footer>

bookshop/templates/includes/header.html
{% load static %}
  <header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'books:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:rgb(255, 255, 255)">Book</span>shop
        </a>
        <form class="form-inline search ml-3" action="{% url 'books:search_results' %}" method="get">
          <i class="fas fa-search mr-2"></i>
          <input name="q" class="form-control mr-sm-2" type="text" autocomplete="off" placeholder="Search">
        </form>
        <ul class="nav nav-pills">
          {% with request.resolver_match.view_name as view_name %}
                    
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'cart:cart_view' %}active{% endif %}" href="{% url 'cart:cart_view' %}">
              Cart
              {% if total_items > 0 %}
                 - <span class="nav-item" >{{ total_items }}</span>
              {% endif %}
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link {% if view_name == 'users:profile' %}active{% endif %}" href="{% url 'users:profile' %}">User: {{ user.username }}</a>
          </li>
          {% else %}
          <li class="nav-item">              
            <a class="nav-link 
               {% if view_name  == 'users:login' %}active{% endif %}"
               href="{% url 'users:login' %}"
            >
            Login
            </a>
          </li>
          <li class="nav-item">              
            <a class="nav-link 
               {% if view_name  == 'users:signup' %}active{% endif %}"
               href="{% url 'users:signup' %}"
            >
            Sign up
            </a>
          </li>
          {% endif %}
          {% endwith %}
        </ul>
        {# Конец добавленого в спринте #}
      </div>
    </nav>
  </header>
  