bookshop/books/urls.py
from django.urls import path

from . import views

app_name = "books"

urlpatterns = [
    path("", views.BooksListView.as_view(), name="index"),
    path("books/<int:pk>/", views.BooksDetailView.as_view(), name="detail"),
    path(
        "books/search/",
        views.SearchResultsListView.as_view(),
        name="search_results"
    ),
]

bookshop/bookshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path("", include("books.urls", namespace="books")),
    path("cart/", include("cart.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]

# handler404 = 'core.views.page_not_found'
# handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    # urlpatterns += static(
    #     settings.STATIC_URL,
    #     document_root=settings.STATIC_ROOT
    # )

bookshop/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_view, name="cart_view"),
    path("add/<int:book_id>/", views.add_to_cart, name="add_to_cart"),
    path(
        "remove/<int:item_id>/",
        views.remove_from_cart,
        name="remove_from_cart"
    ),
    path('config/', views.stripe_config),
    path(
        'create-checkout-session/',
        views.create_checkout_session,
        name='checkout2'
    ),
    path('success/', views.SuccessView.as_view()),
    path('cancelled/', views.CancelledView.as_view()),
]

bookshop/cart/models.py
from django.contrib.auth.models import User
from django.db import models

from books.models import Book


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart of {self.user.username}"

    @property
    def total_quantity(self):
        return sum(item.quantity for item in self.items.all())

    @property
    def total_price(self):
        return sum(item.subtotal for item in self.items.all())


class CartItem(models.Model):
    cart = models.ForeignKey(
        Cart, related_name="items", on_delete=models.CASCADE
    )
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.book.title}"

    @property
    def subtotal(self):
        return self.quantity * self.book.price

bookshop/cart/forms.py
from django import forms

from .models import CartItem


class CartItemForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ["book", "quantity"]

bookshop/cart/views.py
import json

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelform_factory
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, TemplateView

from books.models import Book

from .models import Cart, CartItem
from .utils import (create_line_items, create_stripe_checkout_session,
                    get_cart_with_items)


@login_required
def cart_view(request):
    cart, created = Cart.objects.get_or_create(user=request.user)
    print(">>> request.user", request.user)
    total_items = cart.total_quantity
    context = {"cart": cart, "total_items": total_items}
    return render(request, "cart/cart.html", context)


@login_required
def add_to_cart(request, book_id):
    book = get_object_or_404(Book, id=book_id)

    if not book.book_available:
        return redirect("books:detail", pk=book_id)

    cart, _ = Cart.objects.get_or_create(user=request.user)
    cart_item, _ = CartItem.objects.get_or_create(cart=cart, book=book)

    if request.method == "POST":
        form = modelform_factory(CartItem, fields=["quantity"])(
            request.POST, instance=cart_item
        )
        if form.is_valid():
            cart_item.quantity = form.cleaned_data["quantity"]
            cart_item.save()
            return redirect("cart:cart_view")
    else:
        form = modelform_factory(
            CartItem, fields=["quantity"]
        )(instance=cart_item)

    return render(
        request, "cart/add_to_cart.html", {"form": form, "book": book}
    )


@login_required
def remove_from_cart(request, item_id):
    cart_item = get_object_or_404(
        CartItem, id=item_id, cart__user=request.user
    )
    cart_item.delete()
    return redirect("cart:cart_view")


class CartCheckoutView(LoginRequiredMixin, DetailView):
    model = Cart
    template_name = "cart/checkout.html"
    login_url = "login"

    def get_queryset(self):
        return Cart.objects.filter(user=self.request.user).prefetch_related(
            'items__book'
        )


@csrf_exempt
def stripe_config(request):
    if request.method == 'GET':
        stripe_config = {'publicKey': settings.STRIPE_PUBLISHABLE_KEY}
        return JsonResponse(stripe_config, safe=False)


@csrf_exempt
@login_required
def create_checkout_session(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        cart_id = data.get('cart_id')

        cart = get_cart_with_items(cart_id, request.user)
        if not cart:
            return JsonResponse({'error': 'Cart not found'}, status=404)

        line_items = create_line_items(cart)

        domain_url = 'http://localhost:8000/'
        try:
            checkout_session = create_stripe_checkout_session(
                line_items,
                domain_url,
                cart
            )
            cart.items.all().delete()
            return JsonResponse({'sessionId': checkout_session['id']})
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=400)
    else:
        return JsonResponse({'error': 'Invalid request method'}, status=400)


# @csrf_exempt
# def stripe_webhook(request):
#     payload = request.body
#     sig_header = request.META['HTTP_STRIPE_SIGNATURE']
#     event = None

#     try:
#         event = stripe.Webhook.construct_event(
#             payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
#         )
#     except ValueError as e:
#         return HttpResponse(status=400)
#     except stripe.error.SignatureVerificationError as e:
#         return HttpResponse(status=400)

#     if event['type'] == 'checkout.session.completed':
#         session = event['data']['object']

#         clear_cart(session)

#     return HttpResponse(status=200)


class SuccessView(TemplateView):
    template_name = 'cart/success.html'


class CancelledView(TemplateView):
    template_name = 'cart/cancelled.html'

bookshop/templates/cart/add_to_cart.html
{% extends 'base.html' %}

{% block title %}Add {{ book.title }} to Cart{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Add {{ book.title }} to Cart
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Add</button>
          </form>
          <a href="{% url 'books:detail' book.id %}" class="btn btn-link mt-2">Back to Book</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

bookshop/templates/cart/cancelled.html
{% extends 'base.html' %}

{% block title %}Cancelled Payment{% endblock %}

<section class="section">
    <div class="container">
      <p>Your payment was cancelled.</p>
    </div>
</section>

{% block content %}
<div class="container">
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Your payment was cancelled.</h4>
        <p>Your cart is empty now!</p>
    </div>
    <a href="{% url 'books:index' %}" class="btn btn-primary">To the main page</a>
</div>
{% endblock %}

bookshop/templates/cart/cart.html
{% extends 'base.html' %}

{% block title %}Cart{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Your Cart
        </div>
        <div class="card-body">
          <ul class="list-group">
            {% for item in cart.items.all %}
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                  <a href="{% url 'books:detail' item.book.id %}">
                    <h5 class="mb-0">{{ item.book.title }}</h5>
                  </a>
                  <span class="text-muted">{{ item.book.author }}</span>
                </div>
                <div>
                  <span class="badge badge-primary" style="color: blue;">{{ item.quantity }}</span>
                  <span class="badge badge-success" style="color: green;">${{ item.subtotal }}</span>
                  <a href="{% url 'cart:remove_from_cart' item.id %}" class="btn btn-outline-danger btn-sm ml-2">Delete</a>
                </div>
              </li>
            {% empty %}
              <li class="list-group-item">
                Your cart is empty.
              </li>
            {% endfor %}
          </ul>
          {% if cart.items.all %}
            <div class="mt-3">
              <hr>
              <h5>Total:</h5>
              <p>
                Total items: {{ cart.total_quantity }}
              </p>
              <p>
                Total price: ${{ cart.total_price }}
              </p>
            </div>
          {% endif %}
          <div class="mt-4">
            <button class="btn btn-success" id="submitBtn" data-cart-id="{{ cart.id }}">Purchase</button>
            <a href="{% url 'books:index' %}" class="btn btn-primary">Continue Shopping</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

bookshop/templates/cart/success.html
{% extends 'base.html' %}

{% block title %}Success Payment{% endblock %}

{% block content %}
<div class="container">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Your payment succeeded!</h4>
        <p>Thank you for your purchase.</p>
    </div>
    <a href="{% url 'books:index' %}" class="btn btn-primary">To the main page</a>
</div>
{% endblock %}